export enum EnvField {
  NODE_ENV = 'NODE_ENV',
  KAFKA_HOST = 'KAFKA_HOST',
  KAFKA_PORT = 'KAFKA_PORT',
  CLICKHOUSE_URL = 'CLICKHOUSE_URL',
  CLICKHOUSE_USERNAME = 'CLICKHOUSE_USERNAME',
  CLICKHOUSE_PASSWORD = 'CLICKHOUSE_PASSWORD',
  CLICKHOUSE_DATABASE = 'CLICKHOUSE_DATABASE',
}
