export enum EnvField {
  NODE_ENV = 'NODE_ENV',
  SERVER_PORT = 'SERVER_PORT',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_DATABASE = 'DB_DATABASE',
  CLICKHOUSE_URL = 'CLICKHOUSE_URL',
  CLICKHOUSE_USERNAME = 'CLICKHOUSE_USERNAME',
  CLICKHOUSE_PASSWORD = 'CLICKHOUSE_PASSWORD',
  CLICKHOUSE_DATABASE = 'CLICKHOUSE_DATABASE',
}
