services:
  kafka:
    image: bitnami/kafka:3.7
    restart: always
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      ALLOW_PLAINTEXT_LISTENER: yes
  clickhouse:
    image: clickhouse/clickhouse-server:24-alpine
    volumes:
      - ./storage/clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./storage/clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - '8123:8123'
      - '9000:9000'
    depends_on:
      - clickhouse-keeper
  clickhouse-keeper:
    image: clickhouse/clickhouse-keeper:24-alpine
    volumes:
      - ./storage/clickhouse/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
      - '9181:9181'
