name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v6
        if: github.ref == 'refs/heads/main'
        with:
          context: .
          file: apps/backend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/backend:latest

      - name: Build and push gateway
        uses: docker/build-push-action@v6
        if: github.ref == 'refs/heads/main'
        with:
          context: .
          file: apps/gateway/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/gateway:latest

      - name: Build and push event-worker
        uses: docker/build-push-action@v6
        if: github.ref == 'refs/heads/main'
        with:
          context: .
          file: apps/event-worker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/event-worker:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        if: github.ref == 'refs/heads/main'
        with:
          context: .
          file: apps/frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/frontend:latest
